import { useEffect, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { get, patch, send } from './api.js';

const tabs = ['Dashboard', 'Station', 'Crew', 'Experiments', 'Satellites', 'Ground Stations', 'Command Center', 'Alerts'];
const fallback = { summary: { active_crew: 4, active_satellites: 4, unresolved_alerts: 1 }, station: { name: 'Astra Habitat One', altitude_km: 408, velocity_kms: 7.66 }, resources: [{name:'Oxygen',percentage:94,unit:'%'},{name:'Water',percentage:78,unit:'L'},{name:'Power',percentage:86,unit:'kWh'}], alerts: [{alert_id:'demo',alert_type:'LOW_BATTERY',severity:'CRITICAL',message:'Battery critically low: 18%',satellite_code:'SAT-03'}], events: [] };
const statusClass = (value) => `status ${String(value || 'NOMINAL').toLowerCase()}`;

function Metric({ icon, label, value, sub }) { return <article className="metric"><span className="metric-icon">{icon}</span><div><p>{label}</p><h2>{value}</h2>{sub && <small>{sub}</small>}</div></article>; }
function Resource({ resource }) { return <div className="resource"><div><span>{resource.name}</span><b>{resource.percentage}%</b></div><div className="bar"><i style={{ width: `${resource.percentage}%` }} /></div><small>{resource.current_quantity ?? 'Simulated'} {resource.unit}</small></div>; }

function Dashboard({ dashboard, selectSatellite }) {
  const d = dashboard || fallback;
  return <main className="page">
    <div className="page-title"><div><p className="eyebrow">LIVE MISSION OVERVIEW</p><h1>Space Operations Command Center</h1></div><button className="ghost">● Systems nominal</button></div>
    <section className="metrics"><Metric icon="♟" label="ACTIVE CREW" value={d.summary.active_crew ?? 0} sub="On current mission"/><Metric icon="◉" label="SATELLITES" value={d.summary.active_satellites ?? 0} sub="Network online"/><Metric icon="⚠" label="OPEN ALERTS" value={d.summary.unresolved_alerts ?? 0} sub="Needs attention"/><Metric icon="⌁" label="ORBITAL ALTITUDE" value={`${d.station?.altitude_km ?? 408} km`} sub={`${d.station?.velocity_kms ?? 7.66} km/s velocity`}/></section>
    <section className="layout two-one"><div className="panel"><div className="panel-header"><div><p className="eyebrow">ASTRA HABITAT ONE</p><h3>Station resource health</h3></div><span className={statusClass(d.station?.status)}>NOMINAL</span></div><div className="resources">{d.resources.map((r) => <Resource key={r.name} resource={r}/>)}</div><div className="station-map"><span className="module">SCIENCE<br/>LAB</span><span className="hub">COMMAND<br/>HUB</span><span className="module">HABITAT<br/>MODULE</span><span className="module bottom">DOCKING PORT</span></div></div><div className="panel alerts"><div className="panel-header"><h3>Priority alerts</h3><button className="link">View all</button></div>{d.alerts.length ? d.alerts.map(a => <div className="alert" key={a.alert_id}><span className="alert-dot">!</span><div><b>{a.alert_type.replace('_',' ')}</b><p>{a.message}</p><small>{a.satellite_code || a.module_code}</small></div><span className={statusClass(a.severity)}>{a.severity}</span></div>) : <p className="empty">No unresolved alerts.</p>}</div></section>
    <section className="panel fleet"><div className="panel-header"><div><p className="eyebrow">SATELLITE NETWORK</p><h3>Fleet status</h3></div><button className="link" onClick={() => selectSatellite('SAT-03')}>Open SAT-03 →</button></div><SatelliteMiniGrid selectSatellite={selectSatellite}/></section>
  </main>;
}

function SatelliteMiniGrid({ selectSatellite }) { const [satellites, setSatellites] = useState([]); useEffect(() => { get('/satellites').then(setSatellites).catch(() => setSatellites([{code:'SAT-01',purpose:'Earth Observation',battery_pct:91,status:'NOMINAL'},{code:'SAT-02',purpose:'Communication',battery_pct:73,status:'NOMINAL'},{code:'SAT-03',purpose:'Research',battery_pct:18,status:'CRITICAL'},{code:'SAT-04',purpose:'Climate Monitoring',battery_pct:88,status:'NOMINAL'}])); }, []); return <div className="sat-grid">{satellites.map(s => <button className="sat-card" key={s.code} onClick={() => selectSatellite(s.code)}><span>◉ {s.code}</span><b>{s.purpose}</b><p>Battery <strong>{s.battery_pct}%</strong></p><em className={statusClass(s.status)}>{s.status}</em></button>)}</div>; }

function SatelliteDetail({ code }) { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { setData(null); get(`/satellites/${code}`).then(setData).catch(() => setError('Connect the PostgreSQL backend to show live telemetry.')); }, [code]); if (!data) return <main className="page"><div className="page-title"><div><p className="eyebrow">SATELLITE MISSION CONTROL</p><h1>{code} telemetry</h1></div></div><div className="panel loading">{error || 'Loading telemetry…'}</div></main>; const s=data.satellite; return <main className="page"><div className="page-title"><div><p className="eyebrow">{s.purpose}</p><h1>{s.code} — {s.name}</h1></div><span className={statusClass(s.status)}>{s.status}</span></div><section className="metrics"><Metric icon="▣" label="BATTERY" value={`${s.battery_pct}%`}/><Metric icon="⌁" label="ALTITUDE" value={`${s.altitude_km} km`}/><Metric icon="☀" label="SIGNAL" value={`${s.signal_pct}%`}/><Metric icon="♨" label="TEMPERATURE" value={`${s.temperature_c}°C`}/></section><section className="panel chart"><div className="panel-header"><h3>Battery history</h3><span>Last {data.telemetry.length} readings</span></div><ResponsiveContainer width="100%" height={280}><AreaChart data={data.telemetry}><defs><linearGradient id="battery" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#33d6ff" stopOpacity=".5"/><stop offset="1" stopColor="#33d6ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#203351" strokeDasharray="4 4"/><XAxis dataKey="recorded_at" tickFormatter={(v)=>new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}/><YAxis/><Tooltip/><Area type="monotone" dataKey="battery_pct" stroke="#33d6ff" fill="url(#battery)" strokeWidth={3}/></AreaChart></ResponsiveContainer></section></main>; }

function CommandCenter() { const [satelliteCode, setSatelliteCode] = useState('SAT-03'); const [commandType, setCommandType] = useState('SAFE_MODE'); const [result, setResult] = useState(null); const [error, setError] = useState(''); async function createCommand() { try { setError(''); const command = await send('/commands', { satelliteCode, commandType }); setResult(command); } catch (e) { setError(e.message); } } return <main className="page"><div className="page-title"><div><p className="eyebrow">UPLINK OPERATIONS</p><h1>Command Center</h1></div></div><section className="panel command"><div><label>Target satellite</label><select value={satelliteCode} onChange={e=>setSatelliteCode(e.target.value)}><option>SAT-01</option><option>SAT-02</option><option>SAT-03</option><option>SAT-04</option></select></div><div><label>Command</label><select value={commandType} onChange={e=>setCommandType(e.target.value)}>{['SAFE_MODE','RESTART_PAYLOAD','ORIENTATION_CHANGE','REQUEST_TELEMETRY'].map(x=><option key={x}>{x}</option>)}</select></div><button className="primary" onClick={createCommand}>Transmit command →</button>{result && <div className="success">Command {result.command_id.slice(0,8)} created. Status: CREATED</div>}{error && <div className="error">{error}</div>}</section><section className="panel"><h3>Command lifecycle</h3><div className="timeline"><span>1<br/><small>Created</small></span><i/><span>2<br/><small>Transmitted</small></span><i/><span>3<br/><small>Received</small></span><i/><span>4<br/><small>Executed</small></span></div></section></main>; }

function DataPage({ title, eyebrow, path, children }) { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(()=>{ get(path).then(setData).catch(e=>setError(e.message)); },[path]); return <main className="page"><div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div></div>{error ? <section className="panel loading">Start the database/backend to show live records.</section> : !data ? <section className="panel loading">Loading operational data…</section> : children(data, setData)}</main>; }

function Station() { return <DataPage title="Station Operations" eyebrow="ASTRA HABITAT ONE" path="/station">{data=><><section className="metrics"><Metric icon="⌁" label="ORBITAL ALTITUDE" value={`${data.station.altitude_km} km`}/><Metric icon="≫" label="VELOCITY" value={`${data.station.velocity_kms} km/s`}/><Metric icon="▦" label="STATION MODULES" value={data.modules.length}/><Metric icon="◌" label="RESOURCE HEALTH" value={`${data.resources.reduce((a,r)=>a+Number(r.percentage),0)/data.resources.length}%`}/></section><section className="module-grid">{data.modules.map(m=><article className="panel module-card" key={m.module_id}><div className="panel-header"><div><p className="eyebrow">{m.code} · {m.module_type}</p><h3>{m.name}</h3></div><span className={statusClass(m.status)}>{m.status}</span></div><div className="readings"><span>Temp <b>{m.temperature_c}°C</b></span><span>Pressure <b>{m.pressure_kpa} kPa</b></span><span>O₂ <b>{m.oxygen_pct}%</b></span><span>CO₂ <b>{m.co2_pct}%</b></span></div><small>Maintenance: {m.last_maintenance_on || 'Not recorded'}</small></article>)}</section></>}</DataPage>; }

function Crew() { return <DataPage title="Crew & Task Management" eyebrow="HORIZON MISSION · OR-26" path="/crew">{data=><section className="crew-grid">{data.map(c=><article className="panel crew-card" key={c.crew_id}><span className="avatar">{c.full_name.split(' ').map(x=>x[0]).join('')}</span><div><p className="eyebrow">{c.role}</p><h3>{c.full_name}</h3><p>{c.nationality}</p></div><span className={statusClass(c.status)}>ACTIVE</span><div className="crew-stats"><span><b>{c.open_tasks}</b> Open tasks</span><span><b>{c.completed_tasks}</b> Completed</span></div></article>)}</section>}</DataPage>; }

function Experiments() { return <DataPage title="Experiment Control" eyebrow="SCIENCE & RESEARCH" path="/experiments">{data=><section className="experiment-grid">{data.map(e=><article className="panel experiment" key={e.experiment_id}><p className="eyebrow">{e.code} · {e.module_name}</p><h3>{e.title}</h3><p>Lead researcher: <b>{e.lead_researcher}</b></p><div className="bar"><i style={{width:`${e.progress_pct}%`}}/></div><div className="panel-header"><span>{e.progress_pct}% complete</span><span className={statusClass(e.status)}>{e.status}</span></div><small>Started {e.started_on} · {e.log_count} logs</small></article>)}</section>}</DataPage>; }

function GroundStations() { return <DataPage title="Ground Station Network" eyebrow="COMMUNICATION OPERATIONS" path="/ground-stations">{data=><section className="ground-grid">{data.map(g=><article className="panel ground" key={g.ground_station_id}><div className="panel-header"><div><p className="eyebrow">{g.code} · {g.country}</p><h3>{g.city}</h3></div><span className={statusClass(g.status)}>ONLINE</span></div><div className="signal">◒ <b>{g.signal_pct ?? '—'}%</b><span> signal quality</span></div><p>Connected satellite <strong>{g.connected_satellite || 'No active session'}</strong></p><small>{g.latitude}, {g.longitude}</small></article>)}</section>}</DataPage>; }

function Alerts() { const [alerts, setAlerts] = useState(null); const [error, setError] = useState(''); const load=()=>get('/alerts?status=ALL').then(setAlerts).catch(e=>setError(e.message)); useEffect(load,[]); const resolve=async id=>{await patch(`/alerts/${id}/resolve`); load();}; return <main className="page"><div className="page-title"><div><p className="eyebrow">CENTRALIZED MONITORING</p><h1>Alert Center</h1></div></div>{error?<section className="panel loading">Start the database/backend to view alerts.</section>:!alerts?<section className="panel loading">Loading alerts…</section>:<section className="panel alert-table">{alerts.map(a=><div className="alert-row" key={a.alert_id}><span className={statusClass(a.severity)}>{a.severity}</span><div><b>{a.alert_type.replace('_',' ')}</b><p>{a.message}</p><small>{a.satellite_code || a.module_code} · {new Date(a.created_at).toLocaleString()}</small></div><span className={statusClass(a.status)}>{a.status}</span>{a.status!=='RESOLVED'&&<button className="ghost" onClick={()=>resolve(a.alert_id)}>Resolve</button>}</div>)}</section>}</main>; }

export default function App() { const [tab, setTab] = useState('Dashboard'); const [dashboard, setDashboard] = useState(null); useEffect(() => { get('/dashboard').then(setDashboard).catch(() => setDashboard(fallback)); }, []); const openSatellite = (code) => setTab(`Satellite:${code}`); let content = tab === 'Dashboard' ? <Dashboard dashboard={dashboard} selectSatellite={openSatellite}/> : tab.startsWith('Satellite:') ? <SatelliteDetail code={tab.split(':')[1]}/> : tab === 'Station' ? <Station/> : tab === 'Crew' ? <Crew/> : tab === 'Experiments' ? <Experiments/> : tab === 'Ground Stations' ? <GroundStations/> : tab === 'Alerts' ? <Alerts/> : tab === 'Command Center' ? <CommandCenter/> : <SatelliteDetail code="SAT-03"/>; return <div className="app"><aside><div className="brand"><span>◈</span><div>ORBIT<span>OPS</span><small>MISSION CONTROL</small></div></div><nav>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t==='Dashboard'?'◫':t==='Satellites'?'◉':t==='Alerts'?'⚠':'◇'} {t}</button>)}</nav><div className="operator"><span>MR</span><div><b>Maya Raman</b><small>Mission Controller</small></div></div></aside><div className="content"><header><span>● LIVE SIMULATION</span><p>OR-26 · Horizon Mission</p><button onClick={()=>get('/simulator/tick').then(()=>get('/dashboard').then(setDashboard))}>↻ Simulate tick</button></header>{content}</div></div>; }
